name: Run Script on Locale Files

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  find-locales:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.find.outputs.files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find locale JSON files
        id: find
        run: |
          files=$(ls dashboard/public/locales/*.json | jq -R -s -c 'split("\n")[:-1]')
          echo "files=$files" >> "$GITHUB_OUTPUT"

  run-script:
    needs: find-locales
    runs-on: ubuntu-latest

    strategy:
      matrix:
        locale-file: ${{ fromJson(needs.find-locales.outputs.files) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script with locale file
        run: |
          bash tools/check_translations.sh "${{ matrix.locale-file }}"
        shell: bash
